#!/bin/sh

MAC="$(dirname "$0")"


# catch and export parameters
fn=$1
firstParameter=$2
secondParameter=$3
allParameters=${@:2}

export MAC
export fn
export firstParameter
export secondParameter
export allParameters

COMMANDS=(
    list
    info
    lock
    restart
    sleep
    shutdown
    uptime
    mem
    speed
    ports
    ip.loc
    ip.pub
    clock
    battery
    fd.size
    fd.hid
    hid.on
    hid.off
    bt.stat
    bt.on
    bt.off
    wifi.stat
    wifi.scan
    wifi.on
    wifi.off
    wifi.pass
    vpn.start
    vpn.stop
    vpn.ls
    ejectall
    md5
    g.init
    g.clone
    g.log
    g.stat
    g.open
    g.size
    g.re
    g.conf
    g.undo
    g.add
    g.add.all
    g.commit
    g.ac
    g.aca
    g.acp
    g.acap
    g.mv
    g.rm
    g.push
    g.pull
    g.merge
    g.th.bh
    g.th.re.bh
    g.co.bh
    g.co.re.bh
    g.ls.bh
    g.rm.bh
    g.rm.re.bh
    g.lfs.init
    g.lfs.tk
    g.lfs.untk
    g.lfs.ls
    g.lfs.conf
    pdf.html
    wttr
    top10
    starwar
    cal
    cal.week
    cal.mon
    cal.add
    say
    mail
    compose
    compute
    define
    ol.open
    lszip
    unzip
    zip
    lstar
    untar
    tar
)

if [ -z "$fn" ]; then
    fn="list"
fi

if [[ ! " ${COMMANDS[@]} " =~ " ${fn} " ]]; then
    echo "${RED}Command not found: ${NC}"
    echo "$fn"
    echo
    echo "Do you mean: "
    for cmd in "${COMMANDS[@]}"; do
        if test "${cmd#*$fn}" != "$cmd"
        then
            echo "${cmd}"
        fi
    done

    if [ ! -z "$allParameters" -a "$allParameters" != " " ]; then
        echo "${RED}\nParameters: ${NC}"
        echo "$allParameters"
    fi
fi

# Linking plugins
"$MAC/tools/help.sh"
"$MAC/tools/general.sh"
"$MAC/tools/git.sh"
"$MAC/tools/functors.sh"
"$MAC/tools/compressor.sh"
