#!/bin/sh

MAC="$(dirname "$0")"


# catch and export parameters
fn=$1
firstParameter=$2
secondParameter=$3
allParameters=${@:2}

export MAC
export fn
export firstParameter
export secondParameter
export allParameters

COMMANDS=(
    list
    help
    helper
    h
    gen
    git
    g
    fun
    f
    com
    c
    term
    t
    dl
    d
    info
    lock
    restart
    sleep
    shutdown
    uptime
    mem
    speed
    ports
    ip.loc
    ip.pub
    clock
    battery
    fd.size
    fd.hid
    hid.on
    hid.off
    bt.stat
    bt.on
    bt.off
    wifi.stat
    wifi.scan
    wifi.on
    wifi.off
    wifi.pass
    vpn.start
    vpn.stop
    vpn.ls
    ejectall
    md5
    g.init
    g.clone
    g.log
    g.stat
    g.open
    go
    g.size
    g.re
    g.conf
    g.undo
    g.add
    g.add.all
    g.commit
    g.ac
    g.aca
    g.acp
    g.acap
    g.mv
    g.rm
    g.wipe
    g.clean
    g.push
    g.pull
    g.merge
    g.rebase
    g.th.bh
    g.th.re.bh
    g.co.bh
    g.co.re.bh
    g.ls.bh
    g.rm.bh
    g.rm.re.bh
    g.stash
    g.unstash
    g.lfs.init
    g.lfs.tk
    g.lfs.untk
    g.lfs.ls
    g.lfs.conf
    pdf.html
    wttr
    top10
    starwar
    cal
    cal.week
    cal.mon
    cal.add
    say
    mail
    compose
    maps
    compute
    define
    ol.open
    olgo
    pymake
    imshow
    ascii
    vim
    ag
    cat
    lszip
    unzip
    zip
    lstar
    untar
    tar
    s.re
    s.de
    s.ls
    s.at
    s.rm
    s.rm.all
    s.div.h
    s.div.t
    s.go.left
    sl
    s.go.right
    sr
    s.go.up
    su
    s.go.down
    sd
    spx
    s.re.left
    srl
    s.re.right
    srr
    s.re.up
    sru
    s.re.down
    srd
    t.at
    t.ls
    t.de
    t.re
    t.rm
    t.rm.all
    t.div.h
    t.div.v
    t.go.left
    tl
    t.go.right
    tr
    t.go.up
    tu
    t.go.down
    td
    tpx
    t.re.left
    trl
    t.re.right
    trr
    t.re.up
    tru
    t.re.down
    trd
    k.doc
    k.doc.model
    k.doc.layers
    k.doc.preproc
    k.doc.train
    k.doc.utils
)

if [ -z "$fn" ]; then
    fn="list"
fi

if [[ ! " ${COMMANDS[@]} " =~ " ${fn} " ]]; then
    echo "${RED}Command not found: ${NC}"
    echo "$fn"
    echo
    echo "Do you mean: "
    for cmd in "${COMMANDS[@]}"; do
        if test "${cmd#*$fn}" != "$cmd"
        then
            echo "${cmd}"
        fi
    done

    if [ ! -z "$allParameters" -a "$allParameters" != " " ]; then
        echo "${RED}\nParameters: ${NC}"
        echo "$allParameters"
    fi
fi

# Linking plugins
"$MAC/tools/help.sh"
"$MAC/tools/general.sh"
"$MAC/tools/git.sh"
"$MAC/tools/functors.sh"
"$MAC/tools/compressor.sh"
"$MAC/tools/multiterm.sh"
"$MAC/tools/dl.sh"
