#!/bin/sh

case "$fn" in
    "list"|"help")
        echo "Mac OS X Terminal Tools"
        echo "=============================================================="
        echo "mac list/help : List all the available commands."
        echo "mac info      : Get OS X version information"
        echo "mac lock      : Lock your mac"
        echo "mac restart   : Restart your mac"
        echo "mac shutdown  : Shutdown your mac"
        echo "mac uptime    : Get the time since last restart"
        echo "mac mem       : Get the memory status"
        echo "mac speed     : Network speed test (with npm's fast-cli package)"
        echo "mac ports     : List all used ports"
        echo "mac ip.loc    : Get Local IP address"
        echo "mac ip.pub    : Get Public IP address"
        echo "mac sleep     : Put your mac into sleep mode"
        echo "mac clock     : Show a clock at the top right of your terminal"
        echo "mac battery   : Show battery status"
        echo "mac fd.size   : Show the folder size."
        echo "mac fd.hid    : List only hidden files in the folder."
        echo "mac hid.on    : Show hidden folders in Finder"
        echo "mac hid.off   : Hide hidden dolfers in Finder"
        echo "mac bt.stat   : Show the bluetooth status"
        echo "mac bt.on     : Turn the bluetooth ON"
        echo "mac bt.off    : Turn the bluetooth OFF"
        echo "mac wifi.stat : Show the status of WiFi"
        echo "mac wifi.scan : Scan available WiFI"
        echo "mac wifi.on   : Turn your WiFi service ON"
        echo "mac wifi.off  : Turn your WIFI service OFF"
        echo "mac wifi.pass : Get WiFi password"
        echo "mac ejectall  : Eject all mounted volumes"
        echo "--------------------------------------------------------------"
        echo "Git Related"
        echo "mac g.log      : Get the log of the project"
        echo "mac g.stat     : Print the status of the proejct"
        echo "mac g.open     : Open the Git repo from URL"
        echo "mac g.size     : Calculate the size of Git Repo"
        echo "mac g.add      : Add an push/pull origin"
        echo "mac g.conf     : List the git configuration"
        echo "mac g.undo     : Undo last commit"
        echo "mac g.push     : Push to current branch"
        echo "mac g.pull     : Pull to current branch"
        echo "mac g.merge    : Merge a specific branch"
        echo "mac g.th.bh    : Touch (create) a new branch"
        echo "mac g.th.re.bh : Touch (clone) a remote branch"
        echo "mac g.co.bh    : Checkout a existing branch"
        echo "mac g.co.re.bh : Checkout a remote branch"
        echo "mac g.ls.bh    : List all the branch"
        echo "mac g.rm.bh    : Remove a local branch"
        echo "mac g.rm.re.bh : Remove a branch from local and remote"
        echo "--------------------------------------------------------------"
        echo "Functors - extra tools"
        echo "mac pdf.html   : Convert a PDF to HTML via pdf2htmlEX"
        echo "mac wttr       : Show the weather for a city."
        echo "mac top10      : Show the top10 used shell commands."
        echo "mac starwar    ; Text based Starwar IV"
        echo "--------------------------------------------------------------"
        echo "Compressor"
        echo "mac lszip      : List file in a ZIP archive."
        echo "mac zip        : Zip a file or folder."
        echo "mac unzip      : Unzip a file or folder."
        echo "mac lstar      : List file in a tar archive."
        echo "mac tar        : Tar a file or folder."
        echo "mac untar      : Untar a file or folder."
        echo "=============================================================="
esac
